# frozen-string-literal: true

require 'sequel_tools'

base_config = { dbadapter: 'postgres', dbname: 'sequel_tools_test',
  username: 'sequel_tools_user' }

namespace 'db' do
  SequelTools.inject_rake_tasks base_config, self
end

namespace 'dbpw' do
  SequelTools.inject_rake_tasks base_config.merge(dbname: 'sequel_tools_test_pw',
                                                  password: 'secret'), self
end

dbtest_config = base_config.merge(dbname: 'sequel_tools_test_test',
                                  maintenancedb: 'sequel_tools_test',
                                  dump_schema_on_migrate: true)
namespace 'dbtest' do
  SequelTools.inject_rake_tasks dbtest_config, self
end

namespace 'dbtestverbose' do
  SequelTools.inject_rake_tasks dbtest_config.merge(log_level: :info), self
end

namespace 'dbtest_schema_table' do
  SequelTools.inject_rake_tasks dbtest_config.merge(schema_table: :custom_schema_mig), self
end
