# frozen-string-literal: true

require 'bundler/setup'
require 'sequel_tools'

base_config = SequelTools.base_config project_root: File.expand_path(__dir__),
  dbadapter: 'postgres', dbname: 'sequel_tools_test', username: 'sequel_tools_user'

namespace 'db' do
  SequelTools.inject_rake_tasks base_config, self
end

namespace 'dbpw' do
  SequelTools.inject_rake_tasks base_config.merge(dbname: 'sequel_tools_test_pw',
                                                  password: 'secret'), self
end

namespace 'dbtest' do
  SequelTools.inject_rake_tasks base_config.merge(dbname: 'sequel_tools_test_test',
                                                  maintenancedb: 'sequel_tools_test',
                                                  dump_schema_on_migrate: true), self
end
